
import axios from "axios";
import { columns } from "./table/column";
import { DataTable } from "./table/data-table";
import React from "react";


export const metadata = {
  title: "Pelamar",
  description: "Generated by create next app",
};


async function getTasks() {
  try {
    const response = await axios.get(`${process.env.BASE_URL}/api/pelamar`);

    if (response.status !== 200) {
      throw new Error("Failed to fetch tasks");
    }

    const tasks = response.data;
    return tasks; // Return data directly without schema validation
  } catch (error) {
    console.error("Failed to fetch tasks:", error);
    return [];
  }
}
const Pelamar = async () => {
  const tasks = await getTasks();
  return (
    <div>
      <DataTable data={tasks} columns={columns} />
    </div>
  );
};

export default Pelamar;
