import TestPage, { DataTableDemo } from '@/components/table';
import React from 'react'
export const metadata = {
  title: "Pelamar",
  description: "Generated by create next app",
};
 const Pelamar = () => {
  return (
    <div>
    <DataTableDemo />
    </div>
  )
}

export default Pelamar
