
import axios from "axios";
import { columns } from "./table/column";
import { DataTable } from "./table/data-table";
import React from "react";
import { Button } from "../../components/ui/button";


export const metadata = {
  title: "Pelamar",
  description: "Generated by create next app",
};


async function getTasks() {
  try {
    const response = await axios.get(`${process.env.BASE_URL}/api/pelamar`);

    if (response.status !== 200) {
      throw new Error("Failed to fetch tasks");
    }

    const tasks = response.data;
    return tasks; // Return data directly without schema validation
  } catch (error) {
    // console.error("Failed to fetch tasks:", error);
    return [];
  }
}
const Pelamar = async () => {
  const tasks = await getTasks();
  return (
    <div>
      <header className="px-5 py-3 flex items-center justify-between border-b h-[70px] w-full border-stroke">
        <div>
          <h3 className="text-[22px] font-semibold">Pelamar</h3>
          <p className="text-[11px] text-muted-foreground font-medium">
            <span className="text-slate-900 font-semibold">320</span> Pelamar
          </p>
        </div>
        <Button className="text-xs px-5 py-2" size="none" variant="green">Add Pelamar</Button>
      </header>
      <DataTable data={tasks} columns={columns}  />
    </div>
  );
};

export default Pelamar;
