

import ClientLayout from "@/components/layout/ClientLayout";
import Banner from "../components/Banner";

export const metadata = {
  title: "halaman-utama",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <ClientLayout className="w-full">
      <Banner />
    </ClientLayout>
  );
}
