import Banner from "../components/Banner";
import NavbarBanner from "../components/Banner/nav";
import Footer from "../components/footer";

export const metadata = {
  title: "Halaman utama",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="w-full">
      <NavbarBanner />
      <Banner />
      <Footer />
    </div>
  );
}
