"use client"

import ClientLayout from "../../../components/layout/ClientLayout";
import React, { useState } from "react";
import { Button } from "../../../components/ui/button";
import { Card } from "../../../components/ui/card";
import axios from "axios";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "../../../components/ui/tabs";
import Cookies from "js-cookie";
import BasicInfo from "./BasicInfo";
import FormPhoto from "./photo";
import Alamat from "./alamat";
import FormPendidikan from "./pendidikan";
import PengalamanKerja from "./pengalaman-kerja";
import Pelatihan from "./pelatihan";
import InfoLanjutan from "./infoLanjutan";

// export const metadata = {
//   title: "Profile",
//   description: "Generated by create next app",
// };

const DataDIri = () => {
  const [basicInfoData, setBasicInfoData] = useState({});
  const [infoLanjutan, setInfoLanjutan] = useState({});
  const [pendidikanData, setPendidikanData] = useState({});
  const [photoData, setPhotoData] = useState({});
  
  // Fungsi untuk handle save semua data
  const handleSave = async () => {
    try {
      // Gabungkan semua data dari form
      const combinedData = {
        ...basicInfoData,
        ...infoLanjutan,
        ...pendidikanData,
        ...photoData
      };

       console.log("Combined Data:", combinedData);
       console.log(
         "PUT URL:",
         `${process.env.NEXT_PUBLIC_API_URL}/api/pelamar/${Cookies.get("id")}`
       );
       console.log("Token:", Cookies.get("refreshToken"));
      // Kirim data ke server menggunakan axios
      const response = await axios.put(
        `${process.env.NEXT_PUBLIC_API_URL}/api/pelamar/${Cookies.get("id")}`, // asumsikan 'id' ada di basicInfoData
        combinedData,
        {
          headers: {
            Authorization: `Bearer ${Cookies.get("refreshToken")}`, // Jika butuh autentikasi token
          },
        }
      );

      alert("Data saved successfully.");
    } catch (error) {
      if (error.response) {
        // The request was made, and the server responded with a status code that falls out of the range of 2xx
        console.error("Server Error:", error.response.data);
        alert(`Failed to save data: ${error.response.data.message}`);
      } else if (error.request) {
        // The request was made, but no response was received
        console.error("No Response:", error.request);
        alert("Failed to save data: No response from the server.");
      } else {
        // Something happened in setting up the request that triggered an Error
        console.error("Error:", error.message);
        alert("Failed to save data.");
      }
    }
  };
  return (
    <ClientLayout>
      <div className="sm:px-8 px-5 mt-5 w-full">
        <Tabs defaultValue="profile" className="mt-5">
          <div className="flex items-center justify-between">
            <TabsList className="grid grid-cols-3  w-full max-w-[400px]">
              <TabsTrigger value="profile" className="text-xs">
                Data Diri
              </TabsTrigger>
              <TabsTrigger value="pengalaman_kerja" className="text-xs">
                Pengalaman
              </TabsTrigger>
              <TabsTrigger value="pelatihan" className="text-xs">
                Pelatihan
              </TabsTrigger>
            </TabsList>
            <TabsContent value="profile">
              <Button
                variant="outline"
                size="none"
                className="bg-greent hover:bg-greent/85 hover:text-white text-white text-xs px-8 ms-3 py-2 shadow-sm"
                onClick={handleSave}
              >
                Save
              </Button>
            </TabsContent>
          </div>
          <TabsContent value="profile" className="w-full col-span-2">
            <div className="w-full grid grid-cols-1 sm:grid-cols-3 mt-4  gap-4">
              <BasicInfo setBasicInfoData={setBasicInfoData} />
              <FormPhoto
                setPhotoData={setPhotoData}
                enctype="multipart/form-data"
              />
            </div>
            <div className="w-full grid grid-cols-1 sm:grid-cols-3 gap-4">
              <InfoLanjutan setInfoLanjutan={setInfoLanjutan} />
              <FormPendidikan setPendidikanData={setPendidikanData} />
            </div>
          </TabsContent>

          <TabsContent value="pengalaman_kerja">
            <Card>
              <PengalamanKerja />
            </Card>
          </TabsContent>
          <TabsContent value="pelatihan">
            <Card>
              <Pelatihan />
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </ClientLayout>
  );
};

export default DataDIri;
