"use client"

import ClientLayout from "../../../components/layout/ClientLayout";
import React, { useState } from "react";
import { Button } from "../../../components/ui/button";
import { Card } from "../../../components/ui/card";
import axios from "axios";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "../../../components/ui/tabs";
import Cookies from "js-cookie";
import BasicInfo from "./BasicInfo";
import FormPhoto from "./photo";
import Alamat from "./alamat";
import FormPendidikan from "./pendidikan";
import PengalamanKerja from "./pengalaman-kerja";
import Pelatihan from "./pelatihan";

// export const metadata = {
//   title: "Profile",
//   description: "Generated by create next app",
// };

const DataDIri = () => {
  const [basicInfoData, setBasicInfoData] = useState({});
  const [alamatData, setAlamatData] = useState({});
  const [pendidikanData, setPendidikanData] = useState({});
  
  // Fungsi untuk handle save semua data
  const handleSave = async () => {
    try {
      // Gabungkan semua data dari form
      const combinedData = {
        ...basicInfoData, // Data dari BasicInfo
        ...alamatData, // Data dari Alamat
        ...pendidikanData, // Data dari Pendidikan
      };

      // Kirim data ke server menggunakan axios
      const response = await axios.put(
        `${process.env.NEXT_PUBLIC_API_URL}/api/pelamar/${Cookies.get("id")}`, // asumsikan 'id' ada di basicInfoData
        combinedData,
        {
          headers: {
            Authorization: `Bearer ${Cookies.get("refreshToken")}`, // Jika butuh autentikasi token
          },
        }
      );

      alert("Data saved successfully.");
    } catch (error) {
      console.error("Error saving data:", error);
      alert("Failed to save data.");
    }
  };
  return (
    <ClientLayout>
      <div className="sm:px-8 px-5 mt-5 w-full">
        <Tabs defaultValue="profile" className="mt-5">
          <div className="flex items-center justify-between">
            <TabsList className="grid grid-cols-3  w-full max-w-[400px]">
              <TabsTrigger value="profile" className="text-xs">
                Data Diri
              </TabsTrigger>
              <TabsTrigger value="pengalaman_kerja" className="text-xs">
                Pengalaman
              </TabsTrigger>
              <TabsTrigger value="pelatihan" className="text-xs">
                Pelatihan
              </TabsTrigger>
            </TabsList>
            <TabsContent value="profile">
              <Button
                variant="outline"
                size="none"
                className="bg-greent hover:bg-greent/85 hover:text-white text-white text-xs px-8 ms-3 py-2 shadow-sm"
                onClick={handleSave}
              >
                Save
              </Button>
            </TabsContent>
          </div>
          <TabsContent value="profile" className="w-full col-span-2">
            <div className="w-full grid grid-cols-1 sm:grid-cols-3 mt-4  gap-4">
              <BasicInfo setBasicInfoData={setBasicInfoData} />
              <FormPhoto />
            </div>
            <div className="w-full grid grid-cols-1 sm:grid-cols-3 gap-4">
              <Alamat setAlamatData={setAlamatData} />
              <FormPendidikan setPendidikanData={setPendidikanData} />
            </div>
          </TabsContent>

          <TabsContent value="pengalaman_kerja">
            <Card>
              <PengalamanKerja />
            </Card>
          </TabsContent>
          <TabsContent value="pelatihan">
            <Card>
              <Pelatihan />
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </ClientLayout>
  );
};

export default DataDIri;
