import ClientLayout from "../../../components/layout/ClientLayout";
import React from "react";
import { cookies } from "next/headers";
import { accounts, mails } from "./components/data";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../../../components/ui/card";
import { Badge } from "../../../components/ui/badge";
import { Button } from "../../../components/ui/button";
import { HiMiniSignal } from "react-icons/hi2";
import { Mail } from "./components/mail";

export const metadata = {
  title: "List Formasi",
  description: "Generated by create next app",
};

const ListFormasi = () => {
   const layout = cookies().get("react-resizable-panels:layout:mail");
   const collapsed = cookies().get("react-resizable-panels:collapsed");

   const defaultLayout = layout ? JSON.parse(layout.value) : undefined;
   const defaultCollapsed = collapsed ? JSON.parse(collapsed.value) : undefined;
  return (
    <ClientLayout>
      <div className="px-8 mt-5 w-full">
        <h4 className="py-2 font-semibold">List formasi</h4>
        <div className=" flex-col md:flex">
          <Mail
            accounts={accounts}
            mails={mails}
            defaultLayout={defaultLayout}
            defaultCollapsed={defaultCollapsed}
            navCollapsedSize={4}
          />
        </div>
      </div>
    </ClientLayout>
  );
};

export default ListFormasi;
