import ClientLayout from "../../../components/layout/ClientLayout";
import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "../../../components/ui/accordion";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "../../../components/ui/select";
import { Button } from "@/components/ui/button";

export const metadata = {
  title: "Resume",
  description: "Generated by create next app",
};

const Resume = () => {
  return (
    <ClientLayout>
      <div className="sm:px-8 px-5 mt-5 w-full">
        <div className="flex flex-col">
          <p className="text-xl font-semibold">Resume Information</p>
          <span className="text-xs text-slate-600">
            Here you can edit your information
          </span>
        </div>
      </div>
    </ClientLayout>
  );
};

export default Resume;
